### ISSUE TITLE
Fix openapi yaml exposure

### ISSUE THREAD

**Issue by flohoch** [kula-app/OnLaunch#694]
under the url .../api/openapi.yaml it is missing the paths data

**Comment by flohoch** [comment]
the way it should be:
![image](https://github.com/kula-app/OnLaunch/assets/38766452/0b57cac8-e6d3-42ba-ad2c-9bd73cc92bee)

**Comment by flohoch** [comment]
the way it currently is:
![image](https://github.com/kula-app/OnLaunch/assets/38766452/7b8561cc-fd2f-4410-a7ae-913fdf95e0bb)

**Comment by philprime** [comment]
We should consider migrating to [Redoc](https://github.com/Redocly/redoc).

After extracting the `openapi.json` from the HTML code at `/api-docs` I was able to create docs from that file:

```shell
npx @redocly/cli build-docs openapi.json                     
```

**Comment by philprime** [comment]
https://redocly.com/docs/redoc/deployment/react/
