### ISSUE TITLE
automate swagger doc

### ISSUE THREAD

**Issue by flohoch** [kula-app/OnLaunch#861]
find a way to automate the generation of swagger doc

**Comment by flohoch** [comment]
the package nextjs-routes-docs seemed promising at first, but I had trouble making it run:
![image](https://github.com/kula-app/OnLaunch/assets/38766452/a10660d2-3023-4910-9bd0-b389881bddb2)

**Comment by philprime** [comment]
Try testing it in a Visual Studio Code JavaScript Debug Terminal to see where it is thrown

**Comment by philprime** [comment]
Closed by #1107
